name: Deploy 

on:
  push:
    branches:
      - development
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Install modules
        uses: actions/checkout@v4
        run: npm ci
      
      - name: Build dist
        run: npm run build

      - name: Setup pages
        uses: actions/configure-pages@v3

      - name: Upload dist folder
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./dist"
      
      - name: Deploy to Github pages
        id: deployment
        uses: actions/deploy-pages@v1